openapi: 3.0.3
info:
  title: ユーザー管理API
  description: システム内のユーザーを管理するためのAPIです
  version: 1.0.0
paths:
  /users:
    get:
      summary: すべてのユーザーを取得
      description: 登録されているすべてのユーザーのリストを返します
      responses:
        '200': 
          description: ユーザーオブジェクトのJSON配列
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: 新しいユーザーを作成
      description: システムに新しいユーザーを追加します
      requestBody:
        description: システムに追加するためのユーザーオブジェクト
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ユーザーの名前
                  example: サンプル太郎
                email:
                  type: string
                  description: ユーザーのメールアドレス
                  example: sample@example.com
              required:
                - name
                - email
      responses:
        '201':
          description: ユーザーが正常に作成されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: ユーザーの一意の識別子
          example: ID_123456
        name:
          type: string
          description: ユーザーの名前
          example: サンプル太郎
        email:
          type: string
          description: ユーザーのメールアドレス
          example: sample@example.com
      required:
        - id
        - name
        - email